Repository bSI-InfraRoom/IFC-infra-unit-test, pull requests merged in 2021-03, with the labels that each got.

#60 UT spatial structure 5
  SpatialStructure-5/SpatialStructure-5-1.ifc
  SpatialStructure-5/SpatialStructure-5-1.png
  SpatialStructure-5/SpatialStructure-5-2.ifc
  SpatialStructure-5/SpatialStructure-5-2.png
  SpatialStructure-5/readme.md
Labels: IFC4x3_RC3, new, topic:pw

#45 Readme updated and png added
  SpatialStructure-4/SpatialStructure-4-12d-1.png
  SpatialStructure-4/readme.md
Labels: update

#78 accounting for deletions
  .github/workflows/schema-check.yml
Labels: BUG

#33 initial commit project setup 2
  ProjectSetup-2/UT_ProjectSetup_2.ifc
  ProjectSetup-2/UT_ProjectSetup_2.png
  ProjectSetup-2/readme.md
Labels: IFC4x3_RC3, new

#79 removing errors in report generation
  SpatialStructure-4/readme.md
Labels: BUG, documentation

#44 UT-Earthworks-12d-1
  UT-Earthworks-12d-1/UT-Earthworks-12d-1.ifc
  UT-Earthworks-12d-1/UT_Earthworks_12d_1.PNG
  UT-Earthworks-12d-1/readme.md
Labels: IFC4x3_RC3, new

#82 Update Alignment-12d-1 to RC3
  Alignment-12d-1/Alignment-12d-1.ifc
  Alignment-12d-1/Alignment-12d-1.png
  Alignment-12d-1/UT-Alignment-12d-1.ifc
  Alignment-12d-1/readme.md
Labels: IFC4x3_RC3

#83 Update Alignment-12d-2 to RC3
  Alignment-12d-2/Alignment-12d-2.ifc
  Alignment-12d-2/Alignment-12d-2.png
  Alignment-12d-2/UT-Alignment-12d-2.ifc
  Alignment-12d-2/readme.md
Labels: IFC4x3_RC3

#22 UT-Alignment-12d-3
  Alignment-12d-3/Alignment-12d-3.ifc
  Alignment-12d-3/Alignment-12d-3.png
  Alignment-12d-3/readme.md
Labels: IFC4x3_RC3, new

#23 UT-Alignment-12d-4
  Alignment-12d-4/Alignment-12d-4.ifc
  Alignment-12d-4/Alignment-12d-4.png
  Alignment-12d-4/readme.md
Labels: IFC4x3_RC3, new

#24 UT-Alignment-12d-5
  Alignment-12d-5/Alignment-12d-5.ifc
  Alignment-12d-5/Alignment-12d-5.png
  Alignment-12d-5/readme.md
Labels: IFC4x3_RC3, new

#34 initial commit spatial structure 1
  SpatialDecomposition-1/UT_SpatialDecomposition_1.ifc
  SpatialDecomposition-1/UT_SpatialDecomposition_1_1.png
  SpatialDecomposition-1/readme.md
Labels: IFC4x3_RC3, new

#35 initial commit spatial structure 2
  SpatialStructure-2/IR_SLBH-AM_SpatialBreakdown.pptx
  SpatialStructure-2/SpatialStructure_2.ifc
  SpatialStructure-2/SpatialStructure_2.png
  SpatialStructure-2/readme.md
Labels: IFC4x3_RC3, new
