Repository bSI-InfraRoom/IFC-infra-unit-test, pull requests merged in 2021-06, with the labels that each got.

#20 UT-Georeferencing-Tin-12d-3
  Georeferencing-Tin-12d-3/Georeferencing-Tin-12d-3.ifc
  Georeferencing-Tin-12d-3/Georeferencing-Tin-12d-3.png
  Georeferencing-Tin-12d-3/readme.md
Labels: IFC4x3_RC3, new

#21 UT-Georeferencing-Tin-12d-4
  Georeferencing-Tin-12d-4/Georeferencing-Tin-12d-4.ifc
  Georeferencing-Tin-12d-4/Georeferencing-Tin_12d-4.png
  Georeferencing-Tin-12d-4/readme.md
Labels: IFC4x3_RC3, new

#25 UT-Alignment-12d-6
  Alignment-12d-6/Alignment-12d-6.ifc
  Alignment-12d-6/Alignment-12d-6.png
  Alignment-12d-6/readme.md
Labels: IFC4x3_RC3, new

#118 New UT Georeferencing-Survey-12d-4
  Georeferencing-Survey-12d-4/Georeferencing-Survey-12d-4-in-RDF-IFCViewer.png
  Georeferencing-Survey-12d-4/Georeferencing-Survey-12d-4.ifc
  Georeferencing-Survey-12d-4/Georeferencing-Survey-12d-4.png
  Georeferencing-Survey-12d-4/readme.md
Labels: IFC4x3_RC3, new

#128 FixedReferenceSweptAreaSolid-1
  FixedReferenceSweptAreaSolid-1/FixedReferenceSweptAreaSolid-1.ifc
  FixedReferenceSweptAreaSolid-1/FixedReferenceSweptAreaSolid-1.png
  FixedReferenceSweptAreaSolid-1/README.md
Labels: IFC4x3_RC3

#80 Updating Georeferencing-Tin-12d-1 to RC3; removing "UT-"from file names
  Georeferencing-Tin-12d-1/Georeferencing-Tin-12d-1.ifc
  Georeferencing-Tin-12d-1/Georeferencing-Tin-12d-1.png
  Georeferencing-Tin-12d-1/readme.md
Labels: IFC4x3_RC3

#122 Alignment-ACCA-1
  Alignment-ACCA-1/Alignment-ACCA-1.ifc
  Alignment-ACCA-1/Alignment-ACCA-1.png
  Alignment-ACCA-1/README.md
Labels: IFC4x3_RC3

#123 Alignment-ACCA-2
  Alignment-ACCA-2/Alignment-ACCA-2.ifc
  Alignment-ACCA-2/Alignment-ACCA-2.png
  Alignment-ACCA-2/README.md
Labels: IFC4x3_RC3

#120 Properties-1
  Properties-1/Properties-1.ifc
  Properties-1/README.md
Labels: IFC4x3_RC3

#29 UT-Alignment-12d-8
  Alignment-12d-8/Alignment-12d-8.ifc
  Alignment-12d-8/Alignment-12d-8.png
  Alignment-12d-8/readme.md
Labels: IFC4x3_RC3, new

#121 Properties-2
  Properties-2/Properties-2.ifc
  Properties-2/README.md
Labels: IFC4x3_RC3

#88 Unit test for Rumble strip from Indiana DoT
  RumbleStrip-INDOT/FT Plans 1of13 0500430 Typical Section.pdf
  RumbleStrip-INDOT/FT Plans 4of13 0500430 for Contract Services.pdf
  RumbleStrip-INDOT/FT Xsect 2of2 0500430 for Contract Services.pdf
  RumbleStrip-INDOT/PR-Twin-Branch-PavementElements.ifc
  RumbleStrip-INDOT/PavementElements.PNG
  RumbleStrip-INDOT/RumbleStrip-INDOT.ifc
  RumbleStrip-INDOT/SurfaceFeatures.JPG
  RumbleStrip-INDOT/Twin-Branch-Surface-Features.ifc
  RumbleStrip-INDOT/readme.md
Labels: IFC4x3_RC3, topic:road

#26 UT-Alignment-12d-7
  Alignment-12d-7/Alignment-12d-7.ifc
  Alignment-12d-7/Alignment-12d-7.png
  Alignment-12d-7/readme.md
Labels: IFC4x3_RC3, new

#42 UT-Alignment-12-11
  Alignment-12d-11/Alignment-12d-11.ifc
  Alignment-12d-11/Alignment-12d-11.png
  Alignment-12d-11/readme.md
Labels: IFC4x3_RC3, new

#130 updating the report after all the merges
  DrainageSystem-1/Readme.md
  DrainageSystem-2/Readme.md
  Georeferencing-Tin-12d-4/Georeferencing-Tin-12d-4.png
  Report/UnitTest_Report.tex
  RumbleStrip-INDOT/readme.md
  SpatialStructure-4/readme.md
Labels: documentation

#108 MCON-1
  MCON-1/M14334-Cross-section.png
  MCON-1/MCON-1.ifc
  MCON-1/Superelevations-Widths.png
  MCON-1/TOI-M14334-0000A.XML
  MCON-1/TOI-M14334-0000A.ifc
  MCON-1/TOI-Y3-0000A.XML
  MCON-1/TOI-Y3-0000A.ifc
  MCON-1/readme.md
Labels: IFC4x3_RC3, new, topic:road

#124 LinearPlacement-1
  LinearPlacement-1/LinearPlacement-1.ifc
  LinearPlacement-1/LinearPlacement-1.png
  LinearPlacement-1/README.md
Labels: IFC4x3_RC3

#125 LinearPlacement-2
  LinearPlacement-2/LinearPlacement-2.ifc
  LinearPlacement-2/LinearPlacement-2.png
  LinearPlacement-2/README.md
Labels: IFC4x3_RC3

#126 LinearPlacement-3
  LinearPlacement-3/LinearPlacement-3.ifc
  LinearPlacement-3/LinearPlacement-3.png
  LinearPlacement-3/README.md
Labels: IFC4x3_RC3

#127 LinearPlacement-4
  LinearPlacement-4/LinearPlacement-4.ifc
  LinearPlacement-4/LinearPlacement-4.png
  LinearPlacement-4/README.md
Labels: IFC4x3_RC3
