Repository bSI-InfraRoom/IFC-infra-unit-test, pull requests merged in 2021-04, with the labels that each got.

#47 UT-Georeferencing-Earthworks-12d-1
  Georeferencing-Earthworks-12d-1/Georeferencing-Earthworks-12d-1.ifc
  Georeferencing-Earthworks-12d-1/Georeferencing-Earthworks-12d-1.png
  Georeferencing-Earthworks-12d-1/readme.md
Labels: IFC4x3_RC3, new

#87 Earthworks-12d-1: remove "UT-" from file names
  Earthworks-12d-1/Earthworks-12d-1.PNG
  Earthworks-12d-1/Earthworks-12d-1.ifc
  Earthworks-12d-1/readme.md
Labels: IFC4x3_RC3

#58 Spatial structure 1
  SpatialStructure-1/SpatialStructure1.ifc
  SpatialStructure-1/SpatialStructure1.png
  SpatialStructure-1/readme.md
Labels: IFC4x3_RC2, IFC4x3_RC3

#36 initial commit spatial structure 3
  SpatialStructure-3/Figure1-situation.png
  SpatialStructure-3/Figure2-result.png
  SpatialStructure-3/IFCTreeView.PNG
  SpatialStructure-3/SpatialStructure_3.ifc
  SpatialStructure-3/readme.md
Labels: IFC4x3_RC2, new

#81 Updating Georeferencing-Tin_12d-2 to RC3
  Georeferencing-Tin-12d-2/Georeferencing-Tin-12d-2.ifc
  Georeferencing-Tin-12d-2/Georeferencing-Tin-12d-2.png
  Georeferencing-Tin-12d-2/readme.md
Labels: IFC4x3_RC3

#54 UT-Earthworks-12d-0
  Earthworks-12d-0/Earthworks-12d-0.PNG
  Earthworks-12d-0/Earthworks-12d-0.ifc
  Earthworks-12d-0/readme.md
Labels: IFC4x3_RC3, new

#49 UT-Earthworks-12d-2
  Earthworks-12d-2/Earthworks-12d-2.ifc
  Earthworks-12d-2/Earthworks-12d-2.png
  Earthworks-12d-2/readme.md
Labels: IFC4x3_RC3, new

#98 Update check
  .github/workflows/schema-check.yml
  docs/unit-test-instructions.md
Labels: documentation

#86 Report update
  .github/workflows/schema-check.yml
  Borehole-1/Borehole-1.ifc
  Borehole-1/Borehole-1.png
  Borehole-1/readme.md
  Report/UnitTest_Report.tex
  SpatialDecomposition-1/UT_SpatialDecomposition_1.ifc
  SpatialDecomposition-1/UT_SpatialDecomposition_1_1.png
  SpatialDecomposition-1/readme.md
  SpatialStructure-1/readme.md
  SpatialStructure-6/readme.md
Labels: documentation, update

#101 Report update
  Report/UnitTest_Report.tex
Labels: documentation

#37 UT-Earthworks-01
  Earthworks-01/UT-Earthworks-01.dwg
  Earthworks-01/UT-Earthworks-01.ifc
  Earthworks-01/UT-Earthworks-01.png
  Earthworks-01/readme.md
Labels: IFC4x3_RC3, new

#55 UT-Georeferencing-Survey-12d-1
  Georeferencing-Survey-12d-1/Georeferencing-Survey-12d-1.ifc
  Georeferencing-Survey-12d-1/Georeferencing-Survey-12d-1.png
  Georeferencing-Survey-12d-1/readme.md
Labels: IFC4x3_RC3, new

#109 Including OIP screen shots
  Earthworks-12d-0/Earthworks-12d-0-OIP.PNG
  Earthworks-12d-0/Earthworks-12d-0-OIP_2.PNG
  Earthworks-12d-0/readme.md
  Earthworks-12d-1/Earthworks-12d-1-OIP.PNG
  Earthworks-12d-1/readme.md
  Earthworks-12d-2/Earthworks-12d-2-OIP.png
  Earthworks-12d-2/readme.md
Labels: IFC4x3_RC3, update
